### ISSUE TITLE
how did you get performance with flip test??

### ISSUE THREAD

**Issue by Minwookk** [dvlab-research/FocalsConv#14]
can i get command?

**Comment by yukang2017** [comment]
We follow the settings in the original CenterPoint codebase for double flip testing.

You can refer to this for the details.

https://github.com/tianweiy/CenterPoint/blob/3c64610e78756990c8f67732749806a7a83caa5a/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_flip.py#L5
