### ISSUE TITLE
Question about the results on nuscenes

### ISSUE THREAD

**Issue by Solacex** [dvlab-research/FocalsConv#15]
Thanks for your inspiring work. 

I have some questions concerning the results on nuscene.

When do you impose the focal loss [loss_box_of_pts] on nuscenes? I notice that you only employ it with modality fusion but disable it with LiDAR only?  Is there any reason behind this?

**Comment by yukang2017** [comment]
This is because the calculation of gt for each voxel in nuScenes is too slow on nuScenes, as the number of voxels is times of that of KITTI. It will slow down the training time. Thus, I disable this loss for fast training. You can also use it. The performance influenced from this loss is limited.

**Comment by Solacex** [comment]
Thanks for your prompt response!  So how long will it take  when activating this loss than without it?

**Comment by Solacex** [comment]
BTW,  the result of fusion but without FocalConv should be the second line in Table 9 of your paper?   It would be nice if you can share that results with the whole set.

**Comment by yukang2017** [comment]
It takes about 2 to 3 days longer than the experiment that disabling the loss. 

Yes. It is the second line in Table 9. Sorry that we did not train this baseline before on the whole set. I will run this experiment tomorrow and tell you the results this week.

**Comment by Solacex** [comment]
Thanks for your kind response, and look forward to the results!

**Comment by yukang2017** [comment]
Sorry for keeping your waiting. Due to our limited computation resources. I still need 3 days to finish this training. Thanks!

**Comment by Solacex** [comment]
No worries! And thanks for your kindness on reporting this result.

**Comment by yukang2017** [comment]
Hi,

It is finished.


![image](https://user-images.githubusercontent.com/24690867/184635155-516171c5-f79e-4024-a624-1a52b12be7d6.png)

**Comment by Solacex** [comment]
Thanks! It really helps! 
Two minor questions:
1) does this result employ the test-time augmentation? 
2) Which part of the BNs should be fixed?

**Comment by yukang2017** [comment]
Hi,

1. It does not use the test-time augmentations.
2. Sorry. I did not understand this question. I did not do any special operation on BNs.

**Comment by Solacex** [comment]
Thanks again for your informative response! 
I mention the BN configs because I notice the name of some config files contains fix_bn.

**Comment by yukang2017** [comment]
This name follows the original CenterPoint baseline. 
https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py

**Comment by Solacex** [comment]
OK, great!

**Comment by yukang2017** [comment]
Thanks for your interest in our work. You can contact me by WeChat 13261057196 if there are any further question, in case that I did not check the GitHub issues in time.
