### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by zijianh4** [dvlab-research/FocalsConv#17]
Hi, 
Thanks for your great work! Currently, I am trying to train the model [Voxel R-CNN (Car) + Focals Conv (multimodal)](https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_car_focal_multimodal.yaml) without road_plane. Therefore, I modify the kitti_dataset.yaml and voxel_rcnn_car_focal_multimodal.yaml from `USE_ROAD_PLANE: True` to `USE_ROAD_PLANE: False`. However, I encounter this RuntimeError, and don't know how to fix it. 
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/36258633/186539172-d3d5d7e7-c9cb-4d57-9d01-0c813cd0d989.png">
Could you please help me? Thanks! :)

**Comment by yukang2017** [comment]
I think you can make the program runable by adding find_unused_parameters=true in this line.
https://github.com/dvlab-research/FocalsConv/blob/ff7568e0651886e7a9e0dc8f75b78f11224be4d7/OpenPCDet/tools/train.py#L142

However, I never test it without USE_ROAD_PLANE. Thus, I am not sure about the performance. You can try it.
