### ISSUE TITLE
why split foreground and background features based importance but then combine them for next submaniford conv? 

### ISSUE THREAD

**Issue by FlyingQianMM** [dvlab-research/FocalsConv#19]
Hi, these codes confuse me:

Foreground and background features are splitted  firstly based the predicted importance:

https://github.com/dvlab-research/FocalsConv/blob/875e7b0c931ad7d1b2577c4c2201f228c7314a57/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv.py#L212

but then combine the foreground and background features to be fed into a next submaniford conv:

https://github.com/dvlab-research/FocalsConv/blob/875e7b0c931ad7d1b2577c4c2201f228c7314a57/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv.py#L216

why background features participate in next conv？

**Comment by yukang2017** [comment]
Hi, thanks for your interest in our work.

The steps are:
(1) we split input features into foreground and background ones, based on the importance,
(2) we dilate the foreground features.
(3) we combine the **dilated foreground features** and the background ones.

We do not delete background features. The `x_fore` in the line below is the dilated foreground features.

https://github.com/dvlab-research/FocalsConv/blob/875e7b0c931ad7d1b2577c4c2201f228c7314a57/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv.py#L212

**Comment by FlyingQianMM** [comment]
Thank you so much for the timely reply and detailed answer!

I get the steps are:
(1) predict importance by a submaniford conv
(2) filter foreground centric voxel within importance by a top-k or threshold method
(3) filter important voxel in the kernel size for each foreground centric voxel by a threshold method
(4) add these important voxel into foreground feature, which are your mentioned *dilated foreground features*

Is that right?
