### ISSUE TITLE
lidar-only focal centerpoint config is missing

### ISSUE THREAD

**Issue by konyul** [dvlab-research/FocalsConv#2]
I see centerpoint with multimodal focalsconv , but can not find centerpoint with unimodal focalsconv version. So I made new config myself changing centerpoint config from voxelnet to voxelfocal, from spmiddleresnetfhd to spmiddleresnetfhdfocal with use_img = false. Is it right way to do so??

**Comment by konyul** [comment]
I added special_conv_list=[1,2,3] to centerpoint config and now it works

**Comment by yukang2017** [comment]
Note that
    ENLARGE_VOXEL_CHANNELS=64,
is necessary for performance improvement.

Please feel free to reopen this issue if there are any further question.

**Comment by aurorasyu** [comment]
why the setting skip_loss is true? In the paper, there has a supervise using gt.

> Thanks for you interesting on our work. You can use these settings below for backbone settings.
> 
> ```
>     type="SpMiddleResNetFHDFocal", 
>     num_input_features=5, 
>     ds_factor=8,
>     TOPK=True,
>     USE_IMG=False,
>     SKIP_LOSS=True,
>     ENLARGE_VOXEL_CHANNELS=64,
>     SPECIAL_CONV_LIST=[1,2,3],
> ```

why the skip_loss is true? in the paper, there has a supervise using gt.

**Comment by yukang2017** [comment]
This is because the calculation of gt for each voxel in nuScenes is too slow, as the number of voxels is times of that of KITTI. It will slow down the training time. Thus, I disable this loss for fast training. You can also use it. The performance influenced from this loss is limited by this loss.

**Comment by aurorasyu** [comment]
Thanks for your answer.
I have another question about the topk. in the code, i find the setting topk is true, but in the paper, it use the importance threahold, so what is the difference between the two setting. And which setting the result of paper used?
I had try use the topk=false, but has the follow problem:
  File "FocalsConv/CenterPoint/det3d/models/backbones/focal_sparse_conv/focal_sparse_conv.py", line 120, in forward
    out, loss_box_of_pts = self._gen_sparse_features(x, imp3_3d, voxels_3d, batch_dict['gt_boxes'] if self.training else None)
  File "FocalsConv/CenterPoint/det3d/models/backbones/focal_sparse_conv/focal_sparse_conv.py", line 93, in _gen_sparse_features
    features_fore, indices_fore, features_back, indices_back = split_voxels(x, b, imp3_3d, voxels_3d, self.kernel_offsets, mask_multi=self.mask_multi, topk=self.topk, threshold=self.threshold)
  File "FocalsConv/CenterPoint/det3d/models/backbones/focal_sparse_conv/utils.py", line 139, in split_voxels
    features_fore, coords_fore = check_repeat(features_fore_cat, coords_fore, sort_first=True)
  File "FocalsConv/CenterPoint/det3d/models/backbones/focal_sparse_conv/utils.py", line 62, in check_repeat
    features, indices = sort_by_indices(features, indices)
  File "FocalsConv/CenterPoint/det3d/models/backbones/focal_sparse_conv/utils.py", line 47, in sort_by_indices
    idx_sum = idx.select(1, 0) * idx[:, 1].max() * idx[:, 2].max() + idx.select(1, 1) * idx[:, 2].max() + idx.select(1, 2)
RuntimeError: operation does not have an identity.
it seems that there is no voxel's importance lager than 0.5.

**Comment by yukang2017** [comment]
Thanks for your interest in our work. 

We use the threshold setting for experiments during the paper submission. But I found that it is a bit unstable for training, especially at the early stage of training on nuScenes. For example, sometimes, few voxels has importance larger than the threshold, as the importance prediction is not learnt well at the beginning. It requires resuming checkpoints at the early epochs training. Thus, I change the threshold setting to topk latter, as they have similar performance and the topk setting is more stable for training.
