### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by TimGor1997** [dvlab-research/FocalsConv#20]
Dear author，when I train the nuscenes model on 4 GPU, 24GB, but it shows CUDA out of memory.
How could I solve this problem?

**Comment by TimGor1997** [comment]
spconv 1.2.1
cuda 10.1
pytorch 1.7.1

**Comment by yukang2017** [comment]
Hi,

I think this is caused from the GPU memory cost from the image branch. You can try to 
(1) reduce the batch size to be 2 on per gpu; 
(2) or reduce the image resolution `image_scale` to be smaller, for example, 1/2, or less.

Both these two trials might have a slight reduction on the performance, but not so large.

**Comment by TimGor1997** [comment]
> spconv 1.2.1 cuda 10.1 pytorch 1.7.1

Thank you for your prompt reply！
I have tried to reduce the batch size, but I couldn't find it in either train.py or any config file, could you please tell me where this hyperparameter is located?
Thanks a lot!

**Comment by TimGor1997** [comment]
Thank you for your prompt reply！
I have tried to reduce the batch size, but I couldn't find it in either train.py or any config file, could you please tell me where this hyperparameter is located?
Thanks a lot!

**Comment by yukang2017** [comment]
The batch size is here:
https://github.com/dvlab-research/FocalsConv/blob/875e7b0c931ad7d1b2577c4c2201f228c7314a57/CenterPoint/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_focal_multimodal.py#L220

The image scale ratio is here:
https://github.com/dvlab-research/FocalsConv/blob/875e7b0c931ad7d1b2577c4c2201f228c7314a57/CenterPoint/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_focal_multimodal.py#L29

**Comment by yukang2017** [comment]
It is suggested that you can try to set image_scale = 1/2 first. It has less influence on the performance than batch size, based on my experience.

**Comment by ZecCheng** [comment]
> It is suggested that you can try to set image_scale = 1/2 first. It has less influence on the performance than batch size, based on my experience.

I have tried to train by myself in one 3090 GPU, only change the image_scale from 2/3 to 1/2, and my checkpoint config was nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_focal_multimodal_1_4_data.py. Finally, I got 60.66 mAP and 66.34 NDS.  It drops 1.5mAP and 1.1 NDS from your experiment(image_scale = 2/3)-- 62.15 mAP 67.45 NDS. Is it a normal result based on your experience? 
Thanks for your time!

**Comment by yukang2017** [comment]
Hi,

I think the performance drop is mainly from the reason that you use only single GPU and the global batch size is really small. Based on my experience, using image_scale as 1/2 leads to almost no performance drop.

I suggested that you should use 4 3090 GPUs.


Regards,
Yukang Chen

**Comment by ZecCheng** [comment]
> 

Thanks for your sincere reply 👍
