### ISSUE TITLE
About 2D pretrained model

### ISSUE THREAD

**Issue by yeminglang** [dvlab-research/FocalsConv#22]
Thanks for your excellent work! I notice that 2D pretrained deeplabv3 model on coco dataset is applied. I wonder if you have tested the model with the 2D pretrained model on Cityspaces dataset? Do you think it may lead to better performance? Thanks!
Looking for your reply!

**Comment by yukang2017** [comment]
Hi,

I did not test it  on Cityscape dataset. But I indeed test a 2D model pretrained on nuScenes images. It will generate better performance. The 2D model is obtained from [PETR](https://arxiv.org/abs/2203.05625).
