### ISSUE TITLE
how to generate 1/4 nuscenes data on openpcdet 

### ISSUE THREAD

**Issue by wenchened** [dvlab-research/FocalsConv#24]
hello, you have give the 1/4 nuscenes data in centerpoint based pkl as [infos_train_mini_1_4_10sweeps_withvelo_filter_True.pkl], so i want to now how to generate 1/4 data based on openpcdet.
Thank you very much!

**Comment by yukang2017** [comment]
Hi,

Suppose that you already have the full training pkl file of OpenPCDet, nuscenes_infos_10sweeps_train.pkl

You can open it with 

train_infos = pickle.load(open('nuscenes_infos_10sweeps_train.pkl', 'rb')) 

and filter the 'token' of it to match that of tokens in the 1/4 nuscenes data infos I provided.

For example,

filtered_infos = []
for info in train_infos:
    if info['token'] in info_tokens_1_4:
        filtered_infos.append(info)

And then save the filtered_infos. info_tokens_1_4 is the tokens from that of mine.

**Comment by wenchened** [comment]
Thank you very much!!

**Comment by yukang2017** [comment]
I selected it with an interval of 4.
https://drive.google.com/file/d/19-Zo8o0OWZYed0UpnOfDqTY5oLXKJV9Q/view?usp=sharing

**Comment by wenchened** [comment]
Thanks! It really helps!

**Comment by jyothsna-phd22** [comment]
Hi, can u pl share the complete dataset training pkl file?
