### ISSUE TITLE
Performance variance when using nuscenes 1/4

### ISSUE THREAD

**Issue by konyul** [dvlab-research/FocalsConv#26]
Have you encountered performance fluctuation when using nuscenes 1/4 dataset?
Because I encounter above issue when I train various models on nuscenes 1/7 dataset.

**Comment by yukang2017** [comment]
Hi,

The results on 1/4 nuScenes dataset is a bit stable. The variance is less than 0.5 mAP based on my experience, similar to the whole set. 


Regards,
Yukang Chen
