### ISSUE TITLE
It use too large gpu memory

### ISSUE THREAD

**Issue by blazeCCC** [dvlab-research/FocalsConv#27]
Thank for you excellent work.would anyone could tell me whether this model will cost extra huge gpu memory than offical center point? I only can train this model with batch size  4 on 3090.

**Comment by yukang2017** [comment]
Hi, are your using the multi-modal config？

configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_focal_multimodal.py

I trained it on V100 (32GB) with batch size = 4 per gpu. It indeed costs more GPU memory because image feature processing.

**Comment by blazeCCC** [comment]
> Hi, are your using the multi-modal config？
> 
> configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_focal_multimodal.py
> 
> I trained it on V100 (32GB) with batch size = 4 per gpu. It indeed costs more GPU memory because image feature processing.

i just use lidar only, batch size 3 need almost 17-19 G gpu memory, is this normal?  The size of the point cloud per frame is almost 240,000.

**Comment by yukang2017** [comment]
I think it is normal. You can change this value to be smaller to reduce GPU memory, for example 0.3 instead of 0.5.

https://github.com/dvlab-research/FocalsConv/blob/0ef9df4f5b561d57cf8f35390788894a4cc8e0ce/CenterPoint/det3d/models/backbones/scn_focal.py#L124

**Comment by blazeCCC** [comment]
> I think it is normal. You can change this value to be smaller to reduce GPU memory, for example 0.3 instead of 0.5.
> 
> https://github.com/dvlab-research/FocalsConv/blob/0ef9df4f5b561d57cf8f35390788894a4cc8e0ce/CenterPoint/det3d/models/backbones/scn_focal.py#L124

I see. Thanks for your help

**Comment by yukang2017** [comment]
Thanks for your interests in our work.
