### ISSUE TITLE
How long does it takes to train multimodal FocalsConv on nuScenes dataset?

### ISSUE THREAD

**Issue by rkotimi** [dvlab-research/FocalsConv#5]
Hello @yukang2017! I am trying to train multimodal FocalsConv on 1/4 nuScenes training set with four 2080Ti GPUs.  It is expected to take about six to seven days according to the log. I am not familiar with nuScenes dataset and I wonder if there is something wrong with my environment. So how long do you need to train multimodal FocalsConv on 1/4 nuScenes dataset and the whole dataset?

**Comment by yukang2017** [comment]
Hi, it takes me about one and a half day to train on the 1/4 data on 4 V100 GPUs. 
Empirically, for the nuScenes training, the training speed is highly influenced by the I/O speed for reading data of  your machine. Because there are so many small, separate files in the dataset.

**Comment by rkotimi** [comment]
Thank you for your reply. I will train it with more GPUs.

**Comment by klightz** [comment]
Hi, may I ask a follow up question based on this thread? I find that when training on the multi-modal setting, the training time cost is much larger than the single-model setting, the main time consumption comes from the iteration loop in the 2dnetwork forward and maybe also the fusion part, any idea on this? And may I double confirm that your 1.5 days is for the multi-modal training?

**Comment by konyul** [comment]
How can I see the remaining time for training?
